-- 路径知识库种子数据
-- 生成日期：2025-12-31
-- 注意：收入数据为行业估算，仅供参考

-- ============================================
-- 产品类（product）- 10 条
-- ============================================

INSERT INTO path_templates (id, name, category, description, income_min, income_max, ramp_up_months, suitable_backgrounds, min_weekly_hours, requires_show_face, requires_social, requires_upfront_cost, long_term_no_income, keywords, tips, risks, sort_order, is_active) VALUES

('p001', '开发微型 SaaS', 'product', 
 '开发一个解决特定小众需求的 SaaS 工具，通过订阅制收费。适合有编程能力且能独立完成全栈开发的人。',
 10, 100, 12, 
 ARRAY['技术/开发'], 20,
 false, false, false, true,
 ARRAY['SaaS', '订阅', '独立开发', '被动收入', '全栈', '工具'],
 '建议从自己熟悉的领域入手，先做 MVP 验证市场需求，不要追求完美',
 '可能 6-12 个月无收入，需要有一定储蓄。市场验证失败的概率较高',
 1, true),

('p002', 'Chrome/浏览器插件', 'product',
 '开发浏览器扩展程序解决特定痛点，通过付费版或订阅制变现。开发周期短，适合快速验证想法。',
 5, 50, 6,
 ARRAY['技术/开发'], 10,
 false, false, false, false,
 ARRAY['插件', '浏览器', 'Chrome', '扩展', '效率工具'],
 '关注 Chrome Web Store 热门插件，寻找改进空间或细分方向',
 '插件市场竞争激烈，用户付费意愿普遍较低',
 2, true),

('p003', '付费模板（Notion/Figma）', 'product',
 '制作高质量的 Notion 模板或 Figma UI Kit，在 Gumroad、小报童等平台销售。',
 2, 20, 3,
 ARRAY['设计', '技术/开发'], 10,
 false, false, false, false,
 ARRAY['模板', 'Notion', 'Figma', 'UI', '设计资源', '数字产品'],
 '研究热门模板的设计风格，找到差异化的切入点',
 '模板容易被抄袭，需要持续更新维护',
 3, true),

('p004', '开源项目+赞助', 'product',
 '维护开源项目并通过 GitHub Sponsors、Open Collective 等渠道获得赞助收入。',
 1, 30, 18,
 ARRAY['技术/开发'], 15,
 false, false, false, true,
 ARRAY['开源', 'GitHub', '赞助', '社区', '贡献'],
 '选择解决真实痛点的方向，用心维护社区关系',
 '变现周期很长，收入不稳定，需要持续投入',
 4, true),

('p005', '微信小程序/独立 App', 'product',
 '开发面向 C 端用户的小程序或 App，通过广告、会员或增值服务变现。',
 10, 80, 9,
 ARRAY['技术/开发'], 25,
 false, false, false, false,
 ARRAY['小程序', 'App', '移动端', '微信', 'iOS', 'Android'],
 '优先考虑小程序，开发成本低，获客渠道多',
 '需要持续运营推广，用户留存是挑战',
 5, true),

('p006', 'WordPress 主题/插件', 'product',
 '开发 WordPress 主题或功能插件，在 ThemeForest、CodeCanyon 等平台销售。',
 5, 40, 6,
 ARRAY['技术/开发'], 15,
 false, false, false, false,
 ARRAY['WordPress', '主题', '插件', 'PHP', '建站'],
 '关注市场需求热点，提供优质的售后支持',
 'WordPress 市场相对成熟，需要差异化竞争',
 6, true),

('p007', 'Canva 模板销售', 'product',
 '制作 Canva 设计模板，通过 Canva 创作者计划或第三方平台销售。',
 2, 15, 2,
 ARRAY['设计'], 10,
 false, false, false, false,
 ARRAY['Canva', '模板', '设计', '社交媒体', '平面设计'],
 '关注社交媒体设计趋势，批量生产系列模板',
 '单价低，需要走量，竞争激烈',
 7, true),

('p008', 'PPT/简历模板', 'product',
 '制作精美的 PPT 演示模板或简历模板，在 MAKA、稻壳等平台销售。',
 1, 10, 1,
 ARRAY['设计', '运营/营销'], 5,
 false, false, false, false,
 ARRAY['PPT', '简历', '模板', '演示', '职场'],
 '针对特定行业或场景设计，提高差异化',
 '市场饱和度高，单价极低',
 8, true),

('p009', '表格/自动化工具', 'product',
 '制作 Excel/飞书/Airtable 等表格工具或自动化模板，帮助企业提效。',
 3, 25, 3,
 ARRAY['技术/开发', '运营/营销'], 10,
 false, false, false, false,
 ARRAY['Excel', '表格', '自动化', '飞书', 'Airtable', '效率'],
 '深入了解目标用户的工作流程，解决真实痛点',
 '需要持续维护更新，用户需求多样化',
 9, true),

('p010', '行业垂直工具', 'product',
 '针对特定行业（如餐饮、教育、医疗）开发垂直管理工具。',
 10, 60, 12,
 ARRAY['技术/开发', '传统行业'], 20,
 false, false, false, false,
 ARRAY['垂直', '行业', '管理系统', 'B端', '企业服务'],
 '深入了解行业痛点，与目标客户紧密沟通',
 '获客成本高，需要较强的销售能力',
 10, true);

-- ============================================
-- 内容类（content）- 12 条
-- ============================================

INSERT INTO path_templates (id, name, category, description, income_min, income_max, ramp_up_months, suitable_backgrounds, min_weekly_hours, requires_show_face, requires_social, requires_upfront_cost, long_term_no_income, keywords, tips, risks, sort_order, is_active) VALUES

('c011', '技术博客/SEO 流量站', 'content',
 '创建技术博客或垂直领域内容站，通过广告联盟、付费内容或导流变现。',
 2, 30, 9,
 ARRAY['技术/开发', '内容创作'], 10,
 false, false, false, false,
 ARRAY['博客', 'SEO', '流量', '广告', '内容', '写作'],
 '坚持高质量原创内容，学习基础 SEO 知识',
 '见效慢，需要持续更新，流量起来前收入很低',
 11, true),

('c012', 'YouTube/B站技术频道', 'content',
 '创建技术教程或分享类视频频道，通过平台分成、品牌合作和课程销售变现。',
 5, 100, 12,
 ARRAY['技术/开发', '内容创作'], 15,
 true, false, false, false,
 ARRAY['视频', 'YouTube', 'B站', '教程', '技术分享', 'UP主'],
 '保持更新频率，注重内容质量和观众互动',
 '需要露脸，视频制作有学习曲线',
 12, true),

('c013', '付费专栏（掘金/知乎）', 'content',
 '在技术社区或知识平台开设付费专栏，分享深度技术内容。',
 3, 20, 6,
 ARRAY['技术/开发', '内容创作'], 10,
 false, false, false, false,
 ARRAY['专栏', '掘金', '知乎', '付费', '技术文章', '深度'],
 '选择有深度的垂直方向，建立个人品牌',
 '平台抽成高，用户付费意愿逐年下降',
 13, true),

('c014', '在线课程（网易云课堂等）', 'content',
 '录制系统性技术课程，在教育平台上架销售。',
 5, 50, 6,
 ARRAY['技术/开发', '设计'], 20,
 false, false, false, false,
 ARRAY['课程', '教育', '网易', '培训', '录播', '技术教程'],
 '课程定位要清晰，提供完整的学习路径',
 '课程制作成本高，需要持续更新维护',
 14, true),

('c015', '知识星球/会员社群', 'content',
 '创建付费知识社群，提供独家内容、答疑和交流服务。',
 5, 50, 6,
 ARRAY['技术/开发', '设计', '运营/营销', '内容创作', '销售', '传统行业', '其他'], 10,
 false, true, false, false,
 ARRAY['社群', '知识星球', '会员', '付费', '交流', '圈子'],
 '提供独家价值，维护活跃的社群氛围',
 '需要持续运营，用户续费率是关键挑战',
 15, true),

('c016', '小红书/抖音图文号', 'content',
 '运营小红书或抖音图文账号，通过品牌合作、带货或导流变现。',
 3, 40, 6,
 ARRAY['运营/营销', '内容创作'], 15,
 false, false, false, false,
 ARRAY['小红书', '抖音', '图文', '种草', '带货', '博主'],
 '研究平台算法，保持内容垂直和更新频率',
 '平台规则变化快，流量不稳定',
 16, true),

('c017', '播客节目', 'content',
 '创建音频播客节目，通过广告赞助、付费订阅或衍生产品变现。',
 2, 20, 9,
 ARRAY['内容创作', '技术/开发', '设计', '运营/营销', '销售', '传统行业', '其他'], 10,
 false, false, false, false,
 ARRAY['播客', '音频', 'Podcast', '访谈', '脱口秀'],
 '找到独特的节目定位，保持稳定更新',
 '国内播客市场较小，变现渠道有限',
 17, true),

('c018', '电子书/自出版', 'content',
 '撰写电子书并通过 Kindle、微信读书等平台自出版销售。',
 2, 30, 9,
 ARRAY['内容创作', '技术/开发', '设计', '运营/营销', '销售', '传统行业', '其他'], 15,
 false, false, false, true,
 ARRAY['电子书', 'Kindle', '出版', '写作', '图书'],
 '选择有市场需求的主题，注重内容质量',
 '写书周期长，销量难以预测',
 18, true),

('c019', 'Newsletter 付费订阅', 'content',
 '创建付费邮件订阅服务，定期向订阅者推送独家内容。',
 3, 25, 6,
 ARRAY['内容创作', '运营/营销'], 10,
 false, false, false, false,
 ARRAY['Newsletter', '邮件', '订阅', '内容', '周刊'],
 '提供独家洞见，建立与读者的信任',
 '国内邮件阅读习惯较弱，获客有挑战',
 19, true),

('c020', '短视频/Vlog（不露脸）', 'content',
 '制作不需要露脸的短视频内容（如手绘、剪辑、解说），通过平台分成和合作变现。',
 2, 30, 6,
 ARRAY['内容创作', '设计'], 15,
 false, false, false, false,
 ARRAY['短视频', 'Vlog', '剪辑', '解说', '动画', '不露脸'],
 '找到适合不露脸的内容形式，如动画、PPT讲解',
 '需要较强的后期制作能力',
 20, true),

('c021', '设计素材分享账号', 'content',
 '运营设计相关账号，分享免费素材引流，通过会员或定制服务变现。',
 2, 15, 3,
 ARRAY['设计'], 10,
 false, false, false, false,
 ARRAY['设计', '素材', '分享', '引流', '设计师'],
 '积累粉丝后再考虑变现，先提供价值',
 '版权问题需要注意，变现模式有限',
 21, true),

('c022', '行业分析报告', 'content',
 '撰写深度行业分析报告，通过报告销售或咨询服务变现。',
 5, 40, 6,
 ARRAY['运营/营销', '销售', '传统行业'], 15,
 false, false, false, false,
 ARRAY['报告', '分析', '行业', '调研', '咨询'],
 '选择自己熟悉的行业，提供独到见解',
 '需要较强的分析能力和行业积累',
 22, true);

-- ============================================
-- 服务类（service）- 12 条
-- ============================================

INSERT INTO path_templates (id, name, category, description, income_min, income_max, ramp_up_months, suitable_backgrounds, min_weekly_hours, requires_show_face, requires_social, requires_upfront_cost, long_term_no_income, keywords, tips, risks, sort_order, is_active) VALUES

('s023', '技术外包/接私活', 'service',
 '利用技术能力接外包项目，为客户提供定制开发服务。',
 20, 80, 1,
 ARRAY['技术/开发'], 20,
 false, false, false, false,
 ARRAY['外包', '私活', '接单', '开发', '定制', '项目'],
 '积累作品集，维护好客户关系获取转介绍',
 '收入不稳定，项目管理和沟通成本高',
 23, true),

('s024', '设计外包', 'service',
 '提供平面设计、UI/UX 设计等外包服务。',
 15, 50, 1,
 ARRAY['设计'], 15,
 false, false, false, false,
 ARRAY['设计', '外包', 'UI', 'UX', '平面', '接单'],
 '建立个人作品集和品牌，在设计平台积累口碑',
 '客户需求多变，可能面临无限改稿',
 24, true),

('s025', '咨询顾问', 'service',
 '提供专业领域的咨询服务，按小时或项目收费。',
 10, 100, 3,
 ARRAY['技术/开发', '设计', '运营/营销', '内容创作', '销售', '传统行业', '其他'], 10,
 false, true, false, false,
 ARRAY['咨询', '顾问', '专家', '服务', '建议'],
 '明确自己的专业定位，建立信任背书',
 '需要较强的人脉和行业影响力',
 25, true),

('s026', '代运营（公众号/小红书）', 'service',
 '帮助企业或个人运营社交媒体账号，提供内容策划和发布服务。',
 10, 40, 2,
 ARRAY['运营/营销', '内容创作'], 20,
 false, false, false, false,
 ARRAY['代运营', '公众号', '小红书', '社交媒体', '内容'],
 '建立自己的成功案例，用数据证明效果',
 '客户预期管理难，效果难以量化',
 26, true),

('s027', 'SEO/SEM 服务', 'service',
 '提供搜索引擎优化和付费推广服务，帮助客户获取流量。',
 10, 50, 3,
 ARRAY['运营/营销', '技术/开发'], 15,
 false, false, false, false,
 ARRAY['SEO', 'SEM', '搜索', '优化', '推广', '流量'],
 '用数据说话，建立可量化的成功案例',
 'SEO 效果周期长，SEM 需要持续优化',
 27, true),

('s028', '企业培训讲师', 'service',
 '为企业提供内训服务，传授专业技能或管理方法。',
 15, 80, 6,
 ARRAY['技术/开发', '设计', '运营/营销', '内容创作', '销售', '传统行业', '其他'], 10,
 true, true, false, false,
 ARRAY['培训', '讲师', '企业', '内训', '演讲'],
 '建立培训产品体系，打造个人品牌',
 '需要较强的演讲能力和行业资源',
 28, true),

('s029', '职业规划/简历优化', 'service',
 '提供职业规划咨询和简历优化服务，帮助求职者提升竞争力。',
 5, 30, 2,
 ARRAY['运营/营销', '销售'], 10,
 false, true, false, false,
 ARRAY['职业', '规划', '简历', '求职', '面试', '咨询'],
 '积累成功案例，建立口碑',
 '客单价较低，需要走量',
 29, true),

('s030', '翻译/本地化服务', 'service',
 '提供专业翻译或软件本地化服务。',
 5, 30, 1,
 ARRAY['内容创作', '其他'], 15,
 false, false, false, false,
 ARRAY['翻译', '本地化', '语言', '文档', '多语言'],
 '选择擅长的领域深耕，保证翻译质量',
 '机器翻译冲击大，价格竞争激烈',
 30, true),

('s031', '写作/文案服务', 'service',
 '提供商业文案、软文、脚本等写作服务。',
 5, 25, 1,
 ARRAY['内容创作', '运营/营销'], 10,
 false, false, false, false,
 ARRAY['写作', '文案', '软文', '脚本', '内容'],
 '建立作品集，找到擅长的写作风格',
 '客户需求多样，需要快速适应',
 31, true),

('s032', '数据分析服务', 'service',
 '为企业提供数据分析、报表制作或数据可视化服务。',
 10, 50, 3,
 ARRAY['技术/开发', '运营/营销'], 15,
 false, false, false, false,
 ARRAY['数据', '分析', '报表', '可视化', 'BI'],
 '掌握主流分析工具，建立行业数据分析能力',
 '需要理解业务场景，不仅仅是技术能力',
 32, true),

('s033', '财务/税务咨询', 'service',
 '提供财务规划、税务筹划等专业咨询服务（需相关资质）。',
 10, 60, 3,
 ARRAY['传统行业', '其他'], 10,
 false, true, false, false,
 ARRAY['财务', '税务', '咨询', '会计', '规划'],
 '保持专业学习，建立客户信任',
 '需要专业资质，责任风险较大',
 33, true),

('s034', '法律咨询（持证）', 'service',
 '提供法律咨询服务，如合同审核、法律意见等（需律师资格）。',
 15, 80, 3,
 ARRAY['传统行业', '其他'], 10,
 false, true, false, false,
 ARRAY['法律', '律师', '咨询', '合同', '法务'],
 '选择擅长的细分领域，建立专业口碑',
 '执业风险高，需要持续学习法规更新',
 34, true);

-- ============================================
-- 电商类（ecommerce）- 8 条
-- ============================================

INSERT INTO path_templates (id, name, category, description, income_min, income_max, ramp_up_months, suitable_backgrounds, min_weekly_hours, requires_show_face, requires_social, requires_upfront_cost, long_term_no_income, keywords, tips, risks, sort_order, is_active) VALUES

('e035', '跨境电商（亚马逊/Shopify）', 'ecommerce',
 '在亚马逊、Shopify 等平台开店销售产品到海外市场。',
 10, 100, 6,
 ARRAY['销售', '运营/营销'], 30,
 false, false, true, false,
 ARRAY['跨境', '电商', '亚马逊', 'Shopify', '外贸', '出海'],
 '选择有竞争力的产品，了解目标市场法规',
 '前期投入大，库存风险高，汇率波动影响利润',
 35, true),

('e036', '数字产品销售（Gumroad）', 'ecommerce',
 '在 Gumroad、小报童等平台销售电子书、模板、课程等数字产品。',
 2, 30, 3,
 ARRAY['技术/开发', '设计'], 10,
 false, false, false, false,
 ARRAY['数字产品', 'Gumroad', '小报童', '电子书', '销售'],
 '打造一个爆款产品，后续收入相对被动',
 '需要持续推广，单次购买用户难以复购',
 36, true),

('e037', '闲鱼/转转倒卖', 'ecommerce',
 '在二手平台购买低价商品转卖赚取差价。',
 2, 15, 1,
 ARRAY['销售', '技术/开发', '设计', '运营/营销', '内容创作', '传统行业', '其他'], 10,
 false, false, false, false,
 ARRAY['闲鱼', '转转', '二手', '倒卖', '差价'],
 '寻找信息差，关注市场价格波动',
 '利润薄，需要投入大量时间处理交易',
 37, true),

('e038', '淘宝/拼多多店铺', 'ecommerce',
 '在国内电商平台开店，销售自有或代理产品。',
 5, 50, 6,
 ARRAY['销售', '运营/营销'], 25,
 false, false, true, false,
 ARRAY['淘宝', '拼多多', '电商', '开店', '网店'],
 '选择细分品类，注重产品差异化和客户服务',
 '竞争激烈，需要持续投入推广费用',
 38, true),

('e039', '社群团购', 'ecommerce',
 '在私域社群中组织团购活动，赚取佣金或差价。',
 5, 30, 2,
 ARRAY['销售', '运营/营销', '传统行业'], 15,
 false, true, false, false,
 ARRAY['社群', '团购', '私域', '拼团', '带货'],
 '建立信任关系，选择高性价比产品',
 '需要持续维护社群活跃度',
 39, true),

('e040', '虚拟产品代理', 'ecommerce',
 '代理销售软件账号、会员服务等虚拟产品。',
 3, 20, 1,
 ARRAY['销售', '运营/营销'], 10,
 false, false, false, false,
 ARRAY['代理', '虚拟', '账号', '会员', '软件'],
 '选择正规渠道，注意版权和合规问题',
 '利润空间有限，可能面临平台政策风险',
 40, true),

('e041', '联盟营销/Affiliate', 'ecommerce',
 '推广其他商家的产品，按成交获取佣金。',
 2, 30, 3,
 ARRAY['运营/营销', '内容创作'], 10,
 false, false, false, false,
 ARRAY['联盟', 'Affiliate', '推广', '佣金', 'CPS'],
 '选择佣金较高的产品，建立稳定的流量来源',
 '依赖流量，收入波动大',
 41, true),

('e042', '定制产品（手工/个性化）', 'ecommerce',
 '提供定制化的手工艺品或个性化产品服务。',
 5, 30, 3,
 ARRAY['设计', '传统行业'], 20,
 false, false, false, false,
 ARRAY['定制', '手工', '个性化', '原创', '艺术'],
 '打造独特风格，建立品牌溢价',
 '产能有限，规模化困难',
 42, true);

-- ============================================
-- 投资类（investment）- 4 条
-- ============================================

INSERT INTO path_templates (id, name, category, description, income_min, income_max, ramp_up_months, suitable_backgrounds, min_weekly_hours, requires_show_face, requires_social, requires_upfront_cost, long_term_no_income, keywords, tips, risks, sort_order, is_active) VALUES

('i043', '量化交易/自动化投资', 'investment',
 '利用编程能力开发量化交易策略，实现自动化投资。',
 5, 100, 12,
 ARRAY['技术/开发'], 10,
 false, false, true, true,
 ARRAY['量化', '交易', '股票', '基金', '自动化', '算法'],
 '从小资金开始测试，不要all in',
 '高风险，可能亏损本金，需要持续优化策略',
 43, true),

('i044', '房产出租', 'investment',
 '购买房产用于出租，获取稳定的租金收入。',
 5, 30, 1,
 ARRAY['技术/开发', '设计', '运营/营销', '内容创作', '销售', '传统行业', '其他'], 5,
 false, false, true, false,
 ARRAY['房产', '出租', '租金', '房东', '投资'],
 '选择地段好、好出租的房产',
 '前期投入大，需要处理租客问题',
 44, true),

('i045', '指数基金定投', 'investment',
 '定期定额投资指数基金，通过长期持有获取市场平均收益。',
 2, 20, 36,
 ARRAY['技术/开发', '设计', '运营/营销', '内容创作', '销售', '传统行业', '其他'], 2,
 false, false, true, true,
 ARRAY['基金', '定投', '指数', '理财', '长期'],
 '坚持长期定投，不要频繁操作',
 '市场波动可能导致短期亏损，需要耐心持有',
 45, true),

('i046', '私域流量变现', 'investment',
 '通过积累微信好友、社群等私域流量，进行产品推荐或服务变现。',
 5, 50, 6,
 ARRAY['运营/营销', '销售'], 15,
 false, true, false, false,
 ARRAY['私域', '流量', '微信', '社群', '变现'],
 '提供真实价值，不要过度营销',
 '需要长期维护关系，小心被封号',
 46, true);

-- ============================================
-- 线下类（offline）- 4 条
-- ============================================

INSERT INTO path_templates (id, name, category, description, income_min, income_max, ramp_up_months, suitable_backgrounds, min_weekly_hours, requires_show_face, requires_social, requires_upfront_cost, long_term_no_income, keywords, tips, risks, sort_order, is_active) VALUES

('o047', '技术培训/工作坊', 'offline',
 '举办线下技术培训或工作坊，传授专业技能。',
 10, 50, 3,
 ARRAY['技术/开发'], 15,
 true, true, false, false,
 ARRAY['培训', '工作坊', '线下', '教学', '技术'],
 '从小规模开始，积累口碑和经验',
 '需要场地和组织能力，受地域限制',
 47, true),

('o048', '自由职业者合伙人', 'offline',
 '与其他自由职业者合作，组成松散的团队承接更大项目。',
 20, 80, 3,
 ARRAY['技术/开发', '设计', '运营/营销', '内容创作', '销售', '传统行业', '其他'], 25,
 false, true, false, false,
 ARRAY['合伙', '团队', '自由职业', '协作', '项目'],
 '找到互补技能的合作伙伴，明确分工和利益分配',
 '合作关系需要经营，可能产生分歧',
 48, true),

('o049', '本地服务（摄影/剪辑）', 'offline',
 '提供本地摄影、视频剪辑等服务。',
 10, 40, 2,
 ARRAY['设计', '内容创作'], 20,
 false, false, false, false,
 ARRAY['摄影', '剪辑', '视频', '本地', '服务'],
 '建立作品集，专注于特定类型的拍摄',
 '受地域限制，淡旺季收入波动大',
 49, true),

('o050', '兼职讲师/家教', 'offline',
 '在培训机构或线上平台担任兼职讲师，或提供一对一家教服务。',
 5, 25, 1,
 ARRAY['技术/开发', '设计', '运营/营销', '内容创作', '销售', '传统行业', '其他'], 10,
 true, true, false, false,
 ARRAY['讲师', '家教', '教学', '培训', '兼职'],
 '选择自己擅长的科目，注重教学效果',
 '时间固定，难以规模化',
 50, true);
